// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWelFHChjST-ZVs_PsBDJiA3XBRFj5sDw',
    appId: '1:974498641144:android:58948e8c5a15e3a43db70d',
    messagingSenderId: '974498641144',
    projectId: 'mate8-e545d',
    databaseURL:
        'https://mate8-e545d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mate8-e545d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBuWTm00eTmvag0PHvXonXIFfcWNX47c',
    appId: '1:974498641144:ios:41f292ae084bf6963db70d',
    messagingSenderId: '974498641144',
    projectId: 'mate8-e545d',
    databaseURL:
        'https://mate8-e545d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mate8-e545d.appspot.com',
    iosClientId:
        '974498641144-5fmn74jjr488b72uf8ai4atnj0hgl4u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mate8',
  );
}
